language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev"

services:
  - redis-server

install:
  - pip install -r requirements/tests.txt
  - pip install coveralls
  - pip install -e .

before_script:
  - export DJANGO_SETTINGS_MODULE=tests.travis
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres

script:
  - ./runtests

after_success: coveralls
